// react/App.js
import { useState, useRef, useEffect } from 'react'

function App() {
  // State
  const [todos, setTodos] = useState([])

  // Binding
  const todoText = useRef()

  // Side Effects / Lifecycle
  useEffect(() => {
    const existingTodos = JSON.parse(localStorage.getItem('todos') || [])
    setTodos(existingTodos)
  }, [])

  // Events
  function addTodo(event) {
    event.preventDefault()
    const next = [...todos, todoText.current.value]
    setTodos(next)
    localStorage.setItem('todos', JSON.stringify(next))
  }

  return (
    <div>
      <ul>
        {todos.map(todo => <li key={todo}>{todo}</li>)}
      </ul>

      <form onSubmit={addTodo}>
        <input type="text" placeholder="What needs to be done?" ref={todoText} />
        <input type="submit" value="Add Todo" />
      </form>
    </div>
  );
}

export default App;

// todos/vue/App.vue
<template>
  <div>
    <ul>
      <li v-for="todo in todos" v-bind:key="todo">{{ todo }}</li>
      <form v-on:submit.prevent="addTodo">
        <input v-model="todoText" placeholder="What needs to be done?" />
        <button type="submit">Add Todo</button>
      </form>
    </ul>
  </div>
</template>

<script>
export default {
  name: "HelloWorld",
  data: function () {
    return {
      todos: [],
      todosText: "",
    };
  },
  methods: {
    addTodo: function () {
      this.todos = [...this.todos, this.todoText];
      localStorage.setItem("todos", JSON.stringify(this.todos));
    },
  },
  mounted: function () {
    const existingTodos = localStorage.getItem("todos");
    this.todos = JSON.parse(existingTodos) || [];
  },
};
</script>

<style scoped>
</style>
