// todos/svelte/App.svelte
<script>
  let todos = []
  let todoText = ''

  onMount(() => {
    const existingTodos = localStorage.getItem('todos')
    todos = JSON.parse(existingTodos) || []
  })

  function addTodo() {
    todos = [...todos, todoText]
    localStorage.setItem('todos', JSON.stringify(todos))
  }
</script>

<main>
  <ul>
    {#each todos as todo}
      <li>{todo}</li>
    {/each}
  </ul>

  <form on:submit|preventDefault={addTodo}>
    <input bind:value={todoText} />
    <input type="submit" value="Add todo" />
  </form>
</main>

// todos/vue/App.vue
<template>
  <div>
    <ul>
      <li v-for="todo in todos" v-bind:key="todo">{{ todo }}</li>
      <form v-on:submit.prevent="addTodo">
        <input v-model="todoText" placeholder="What needs to be done?" />
        <button type="submit">Add Todo</button>
      </form>
    </ul>
  </div>
</template>

<script>
export default {
  name: "HelloWorld",
  data: function () {
    return {
      todos: [],
      todosText: "",
    };
  },
  methods: {
    addTodo: function () {
      this.todos = [...this.todos, this.todoText];
      localStorage.setItem("todos", JSON.stringify(this.todos));
    },
  },
  mounted: function () {
    const existingTodos = localStorage.getItem("todos");
    this.todos = JSON.parse(existingTodos) || [];
  },
};
</script>

<style scoped>
</style>
