// todos/svelte/App.svelte
<script>
  let todos = []
  let todoText = ''

  onMount(() => {
    const existingTodos = localStorage.getItem('todos')
    todos = JSON.parse(existingTodos) || []
  })

  function addTodo() {
    todos = [...todos, todoText]
    localStorage.setItem('todos', JSON.stringify(todos))
  }
</script>

<main>
  <ul>
    {#each todos as todo}
      <li>{todo}</li>
    {/each}
  </ul>

  <form on:submit|preventDefault={addTodo}>
    <input bind:value={todoText} />
    <input type="submit" value="Add todo" />
  </form>
</main>

// todos/angular/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  // State
  todos: string[] = []
  todoText = ''

  // Lifecycle
  ngOnInit() {
    const existingTodos = localStorage.getItem('todos')
    this.todos = JSON.parse(existingTodos as string) || []
  }

  //Events
  addTodo() {
    this.todos.push(this.todoText)
    localStorage.setItem('todos', JSON.stringify(this.todos))
  }
}

<ul>
  <li *ngFor="let todo of todos">{{ todo }}</li>
</ul>

<form (ngSubmit)="addTodo()">
  <input name="todotext" [(ngModel)]="todoText">
  <input type="submit" value="Add Todo">
</form>
